services:
  bar:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    # restart: always
    command: "deno --version"

networks:
  shared_network:
    external: true
